
# Cybercat Moccha 
# Normal ANSI colors: saturated / neon
# Bright ANSI colors: lighter / pastel

# General
foreground              #B5FFE2  # Mint
background              #1e1e2e  # Base

# Selection
selection_foreground    #1e1e2e  # Base
selection_background    #94e2d5  # Teal

# Cursor
cursor                  #a6e3a1  # Green
cursor_text_color       #1e1e2e  # Base

# URLs
url_color               #54FFB7  # Neon mint

# Borders
active_border_color     #cdd6f4  # Text
inactive_border_color   #7f849c  # Overlay1
bell_border_color       #fab387  # Peach

# Tabs
active_tab_foreground   #1e1e2e  # Base
active_tab_background   #89b4fa  # Blue
inactive_tab_foreground #a6adc8  # Subtext0
inactive_tab_background #313244  # Surface0
tab_bar_background      #313244  # Surface0


# ANSI Colors

# Black
color0   #45475a  # Surface1
color8   #6c7086  # Overlay0

# Red
color1   #FF5277  # Neon red
color9   #f38ba8  # Soft red

# Green
color2   #34F86C  # Neon green
color10  #75FFA5  # Pastel green

# Yellow
color3   #FFD166  # Neon amber
color11  #f9e2af  # Pastel yellow

# Blue
color4   #7287FD  # Electric indigo
color12  #ADC7FF  # Pastel blue

# Magenta
color5   #D078FF  # Neon violet
color13  #f5c2e7  # Pastel pink

# Cyan
color6   #00FFCC  # Neon cyan
color14  #94e2d5  # Pastel teal

# White
color7   #BAC2DE  # Subtext1
color15  #cdd6f4  # Text
