# Based on Catppuccin Mocha

foreground            #cdd6f4 # text
background            #1e1e2e # base

selection_foreground  #1e1e2e # base
selection_background  #94e2d5 # teal

cursor                 #a6e3a1 # green
cursor_text_color      #1e1e2e # base

url_color              #74c7ec # sapphire

active_border_color    #cdd6f4 # text
inactive_border_color  #7f849c # overlay 1
bell_border_color      #f9e2af

active_tab_foreground    #1e1e2e # base
active_tab_background    #89b4fa # blue
inactive_tab_foreground  #1e1e2e # base
inactive_tab_background  #1e1e2e # base
tab_bar_background       #313244 # surface 0


# ANSI colors

# black
color0   #11111b # crust
color8   #181825 # mantle

# red
color1   #f38ba8 # red
color9   #eba0ac # maroon

# green
color2   #a6e3a1 # green
color10  #a6e3a1 # green

# yellow
color3   #f9e2af # yellow
color11  #fab387 # peach

# blue
color4   #89b4fa # blue
color12  #89dceb # sky

# magenta
color5   #eba0ac # maroon
color13  #f5c2e7 # pink

# cyan
color6   #94e2d5 # teal
color14  #74c7ec # sapphire

# white
color7   #f2cdcd # flamingo
color15  #f5e0dc # rosewater
