# vim:fileencoding=utf-8:foldmethod=marker

# Font
font_family FiraCode Nerd Font Mono
# font_family AtkynsonMono Nerd Font Mono
# italic_font Maple Mono Oblique

font_size 11.0
disable_ligatures cursor

# Bindings
map ctrl+shift+plus change_font_size all +1.0
map ctrl+shift+minus change_font_size all -1.0

# Cursor
shell_integration no-cursor
cursor_shape beam
cursor_shape_unfocused hollow

cursor_beam_thickness 1.5

scrollback_lines 3000

# Padding
window_padding_width 7
window_padding_height 10

# Background
background_opacity 0.9

# TODO: Sound Theming, LOGO and Window Layout
enable_audio_bell no
# bell_path ~/VFX/click.ogg
# linux_bell_theme __custom

#  To change your sound theme
# desktop wide, create
# :file:~/.local/share/sounds/__custom/index.theme` with the
# contents:

#     [Sound Theme]

#     Inherits=name-of-the-sound-theme-you-want-to-use

# Replace name-of-the-sound-theme-you-want-to-use with the actual
# theme name. Now all compliant applications should use sounds from
# this theme.


# Window layout

# remember_window_size  yes
# initial_window_width  640
# initial_window_height 400


# window_logo_path none

#: Path to a logo image. Must be in PNG/JPEG/WEBP/GIF/TIFF/BMP format.
#: Relative paths are interpreted relative to the kitty config
#: directory. The logo is displayed in a corner of every kitty window.
#: The position is controlled by window_logo_position. Individual
#: windows can be configured to have different logos either using the
#: launch action or the remote control
#: <https://sw.kovidgoyal.net/kitty/remote-control/> facility.

# window_logo_position bottom-right

#: Where to position the window logo in the window. The value can be
#: one of: top-left, top, top-right, left, center, right, bottom-left,
#: bottom, bottom-right.

# window_logo_alpha 0.5

#: The amount the logo should be faded into the background. With zero
#: being fully faded and one being fully opaque.

# window_logo_scale 0

foreground            #B5FFDF
background            #282a36
selection_foreground  #CFB67A
selection_background  #44475a

# Colors

include cybercat-mocha.conf
